### ISSUE TITLE
Feature request:  In Timeline mode on a mac, i'd like to use multi-touch to pan left and right

### ISSUE THREAD

**Issue by dheista** [Grix/ildagen#10]
On a Mac, I often use two fingers to swipe up or down, which in Timeline mode zooms the scale up and down.  But when I swipe two fingers left and right, I'd like to pan along the timeline but currently it doesn't do anything.

**Comment by Grix** [comment]
On mac, do you know if this input the same as sideways scrolling on a normal mouse? Or does it need a special implementation that only works on macs?

**Comment by dheista** [comment]
Hmm - good question.  I don't know if this is the same as sideways scrolling on a mouse, but I don't have a mouse in any of my computers (laptops or even desktops all use trackpads), so I can't see if sideways scrolling on a mouse does what I'm looking for.

**Comment by Grix** [comment]
In v1.9.6 you can now use Shift+mouse wheel to scroll horizontally, this seems to be the standard in many other programs. Not sure if this is how the sideways scrolling on mac is implemented under the hood. But if not, then unfortunately it won't be easy for me to fix since I don't have a laptop mac with a touchpad.

**Comment by dheista** [comment]
Oooh - awesome.  Now shift+up/down with two fingers on the trackpad scrolls horizontally!  This is great - a big step up in being able to edit big timelines!
