### ISSUE TITLE
LaserShowGen Pro Timeline Mode Rotate

### ISSUE THREAD

**Issue by drschnalli** [Grix/ildagen#4]
Hello , i bought LSG Pro today. I just want to rotate one part of my show starting from frame x to y by 360 degrees. I have not found a proper solution for that is there no way to draw a straight line into the envelope editor? When i try to draw a line i get thousands of points... and i also only want to rotate a specific part and not to create a rotation track for the whole show. 

![image](https://user-images.githubusercontent.com/22824246/104250974-0829eb00-546f-11eb-8618-0063c7a3b8dd.png)

Maybe you can help me

**Comment by Grix** [comment]
To draw a straight line in the envelope editor, just click on two points in the editor that forms the line, rather than dragging the mouse across it. Since you have already drawn points there you will first have to delete them by holding down D and dragging the mouse over them. And also to avoid rotating everything on the layer, you have to place a point at the end and start to put the line back to its default level.

But another method for rotating that may be better is doing it in the editor mode. You can right click the object where you want the rotation to start, click "Split here", and then do it again where the rotation should end. Then you will end up with a separate object covering only the time period you want the rotation. Then, you can double click this object and it will open in the editor mode. There, you can select all, enable animation, and rotate the objects around the anchor. Then, click "Send to timeline" and it will replace the object you had in the timeline mode, with the rotated version of it.

**Comment by drschnalli** [comment]
Hey Grix, thanks for the idea! Is there a way how i can slowly start rotating and get faster and faster? Can you tell me where i can ask questions like this? As i didnt now i asked here :D

**Comment by Grix** [comment]
In the editor mode you can use the ease-in animation function to make it gradually speed up the rotation:
https://i.imgur.com/u3fCwMW.png
Otherwise if you need more control of the speed, you probably have to use the timeline envelope.

Questions like this can for example be asked on the LSG subreddit, or facebook group, or various forum threads:
https://www.reddit.com/r/lasershowgen/
https://www.facebook.com/lasershowgen
https://www.photonlexicon.com/forums/showthread.php/25505-LasershowGen-now-with-free-edition!
